#!/bin/bash

echo "📋 Top Ollama Models Available:"
echo "================================"
echo ""
echo "🏆 BEST MODELS (2024-2025):"
echo ""
echo "Small (2-4GB):"
echo "  • llama3.2      - Meta's latest, 3B params"
echo "  • phi3          - Microsoft, very efficient"
echo "  • gemma2:2b     - Google's smallest"
echo "  • qwen2.5:3b    - Alibaba's latest"
echo ""
echo "Medium (4-8GB):"
echo "  • llama3.1:8b   - Meta's best 8B model"
echo "  • mistral       - French, very good"
echo "  • gemma2:9b     - Google's medium"
echo "  • deepseek-coder:6.7b - For coding"
echo ""
echo "Large (8-16GB):"
echo "  • llama3.1:70b  - Meta's largest (quantized)"
echo "  • mixtral:8x7b  - Mixture of experts"
echo "  • qwen2.5:14b   - Alibaba's large"
echo "  • deepseek-llm:7b - DeepSeek's base model"
echo ""
echo "Huge (32GB+):"
echo "  • llama3.1:405b - Meta's giant (quantized)"
echo "  • mixtral:8x22b - Massive MoE"
echo ""
echo "To use any model:"
echo "  ollama pull <model-name>"
echo "  ollama run <model-name>"
echo ""
echo "DeepSeek models in Ollama:"
echo "  • deepseek-coder:6.7b"
echo "  • deepseek-coder:33b"
echo "  • deepseek-llm:7b"